// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nvcqacxhfmrykjyvrrbq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im52Y3FhY3hoZm1yeWtqeXZycmJxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA2NjYyMTYsImV4cCI6MjA2NjI0MjIxNn0.3W8_ElOQy6GekIgXCOt4Ubzq30VT8WsClw-SjmpiAT0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);